# src/greenkube/cli/recommend.py
"""
Implements the `recommend` command for the GreenKube CLI.
"""

import logging
import traceback
from typing import Optional

import typer
from typing_extensions import Annotated

from ..core.factory import get_processor
from ..core.recommender import Recommender
from ..reporters.console_reporter import ConsoleReporter

logger = logging.getLogger(__name__)

app = typer.Typer(
    help="Analyze data and provide optimization recommendations.",
    add_completion=False,
)


@app.callback(invoke_without_command=True)
def recommend(
    ctx: typer.Context,
    namespace: Annotated[
        Optional[str],
        typer.Option(help="Display recommendations for a specific namespace."),
    ] = None,
):
    """
    Analyzes data and provides optimization recommendations.
    """
    if ctx.invoked_subcommand is not None:
        return

    logger.info("Initializing GreenKube Recommender...")

    try:
        # 1. Get the processed data
        processor = get_processor()
        logger.info("Running the data processing pipeline...")
        combined_data = processor.run()

        if not combined_data:
            logger.warning("No combined data was generated by the processor. Cannot generate recommendations.")
            raise typer.Exit(code=0)

        # 2. Filter by namespace if provided
        if namespace:
            logger.info(f"Filtering results for namespace: {namespace}...")
            combined_data = [item for item in combined_data if item.namespace == namespace]
            if not combined_data:
                logger.warning(f"No data found for namespace '{namespace}'.")
                raise typer.Exit(code=0)

        # 3. Instantiate Recommender and Reporter
        recommender = Recommender()  # Uses default thresholds
        console_reporter = ConsoleReporter()

        logger.info("Generating recommendations...")

        # 4. Generate recommendations
        zombie_recs = recommender.generate_zombie_recommendations(combined_data)
        rightsizing_recs = recommender.generate_rightsizing_recommendations(combined_data)

        all_recs = zombie_recs + rightsizing_recs

        # 5. Report recommendations
        # If no recommendations, report_recommendations will print the "all clear" message.
        logger.info(f"Found {len(all_recs)} recommendations.")

        console_reporter.report_recommendations(all_recs)

    except typer.Exit:
        raise
    except Exception as e:
        logger.error(f"An error occurred during recommendation generation: {e}")
        logger.error("Recommendation generation failed: %s", traceback.format_exc())
        raise typer.Exit(code=1)
