# tests/integration/test_recommendation_lifecycle_e2e.py
"""
End-to-end integration tests for the full recommendation lifecycle.

These tests exercise the complete business flow:
  1. CombinedMetrics analyzed by the Recommender → Recommendation objects
  2. Recommendations converted to RecommendationRecord objects
  3. Records persisted to SQLite
  4. Records retrieved via the FastAPI layer
  5. Records transitioned (applied / ignored) via the API

This guarantees that recommendations generated by the engine can be safely
stored and managed through the full lifecycle — a critical business requirement.
"""

from datetime import datetime, timezone
from unittest.mock import AsyncMock, patch

import pytest
from fastapi.testclient import TestClient

from greenkube.api.app import create_app
from greenkube.api.dependencies import (
    get_carbon_repository,
    get_combined_metrics_repository,
    get_node_repository,
    get_recommendation_repository,
)
from greenkube.core.db import db_manager
from greenkube.core.recommender import Recommender
from greenkube.models.metrics import (
    CombinedMetric,
    RecommendationRecord,
    RecommendationStatus,
    RecommendationType,
)
from greenkube.storage.sqlite.node_repository import SQLiteNodeRepository
from greenkube.storage.sqlite.recommendation_repository import SQLiteRecommendationRepository
from greenkube.storage.sqlite.repository import SQLiteCarbonIntensityRepository, SQLiteCombinedMetricsRepository

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
async def sqlite_repos():
    """Isolated in-memory SQLite with all required tables."""
    await db_manager.setup_sqlite(db_path=":memory:")
    carbon_repo = SQLiteCarbonIntensityRepository(db_manager)
    combined_repo = SQLiteCombinedMetricsRepository(db_manager)
    node_repo = SQLiteNodeRepository(db_manager)
    reco_repo = SQLiteRecommendationRepository(db_manager)
    yield carbon_repo, combined_repo, node_repo, reco_repo
    await db_manager.close()


@pytest.fixture
def lifecycle_client(sqlite_repos):
    """TestClient wired to real SQLite repositories for lifecycle tests."""
    carbon_repo, combined_repo, node_repo, reco_repo = sqlite_repos

    with patch("greenkube.api.routers.recommendations.HPACollector") as mock_hpa:
        instance = AsyncMock()
        instance.collect = AsyncMock(return_value=set())
        mock_hpa.return_value = instance

        app = create_app()
        app.dependency_overrides[get_carbon_repository] = lambda: carbon_repo
        app.dependency_overrides[get_combined_metrics_repository] = lambda: combined_repo
        app.dependency_overrides[get_node_repository] = lambda: node_repo
        app.dependency_overrides[get_recommendation_repository] = lambda: reco_repo

        with TestClient(app) as c:
            yield c, reco_repo

        app.dependency_overrides.clear()


def _make_zombie_metrics() -> list[CombinedMetric]:
    """Build metrics that will generate a ZOMBIE_POD recommendation."""
    now = datetime.now(timezone.utc)
    return [
        CombinedMetric(
            pod_name="zombie-pod",
            namespace="staging",
            total_cost=0.50,
            co2e_grams=0.1,
            joules=50.0,  # Very low energy despite cost → zombie
            timestamp=now,
            pue=1.2,
            grid_intensity=100.0,
            cpu_usage_millicores=0,
        )
    ]


def _make_oversized_cpu_metrics() -> list[CombinedMetric]:
    """Build a time-series of metrics for a CPU-oversized pod."""
    now = datetime.now(timezone.utc)
    from datetime import timedelta

    return [
        CombinedMetric(
            pod_name="oversized-cpu",
            namespace="production",
            total_cost=1.0,
            co2e_grams=5.0,
            joules=50_000.0,
            timestamp=now - timedelta(hours=i),
            pue=1.2,
            grid_intensity=100.0,
            cpu_request=4000,  # 4 cores requested
            cpu_usage_millicores=200,  # Only 200m used (5%)
        )
        for i in range(48)
    ]


# ---------------------------------------------------------------------------
# Step 1: Recommender generates recommendations from metrics
# ---------------------------------------------------------------------------


class TestRecommenderGeneratesFromMetrics:
    """The Recommender correctly identifies issues in CombinedMetric data."""

    def test_zombie_detected_from_combined_metrics(self):
        """ZOMBIE_POD recommendation is generated from metrics with cost but no energy."""
        recommender = Recommender()
        recs = recommender.generate_recommendations(_make_zombie_metrics())

        zombie_recs = [r for r in recs if r.type == RecommendationType.ZOMBIE_POD]
        assert len(zombie_recs) == 1
        assert zombie_recs[0].pod_name == "zombie-pod"
        assert zombie_recs[0].namespace == "staging"
        assert zombie_recs[0].potential_savings_cost is not None
        assert zombie_recs[0].potential_savings_cost > 0

    def test_cpu_rightsizing_detected_from_combined_metrics(self):
        """RIGHTSIZING_CPU recommendation is generated from consistently low-usage metrics."""
        recommender = Recommender()
        recs = recommender.generate_recommendations(_make_oversized_cpu_metrics())

        cpu_recs = [r for r in recs if r.type == RecommendationType.RIGHTSIZING_CPU]
        assert len(cpu_recs) == 1
        assert cpu_recs[0].pod_name == "oversized-cpu"
        assert cpu_recs[0].recommended_cpu_request_millicores < 4000


# ---------------------------------------------------------------------------
# Step 2: RecommendationRecord conversion
# ---------------------------------------------------------------------------


class TestRecommendationRecordConversion:
    """RecommendationRecord is correctly built from a Recommendation."""

    def test_record_carries_all_recommendation_fields(self):
        """All fields from Recommendation are reflected in RecommendationRecord."""
        recommender = Recommender()
        recs = recommender.generate_recommendations(_make_zombie_metrics())
        zombie_rec = next(r for r in recs if r.type == RecommendationType.ZOMBIE_POD)

        record = RecommendationRecord.from_recommendation(zombie_rec)

        assert record.pod_name == zombie_rec.pod_name
        assert record.namespace == zombie_rec.namespace
        assert record.type == zombie_rec.type
        assert record.priority == zombie_rec.priority
        assert record.potential_savings_cost == zombie_rec.potential_savings_cost
        assert record.status == RecommendationStatus.ACTIVE

    def test_record_default_status_is_active(self):
        """Freshly created records must have ACTIVE status."""
        recommender = Recommender()
        recs = recommender.generate_recommendations(_make_zombie_metrics())
        record = RecommendationRecord.from_recommendation(recs[0])

        assert record.status == RecommendationStatus.ACTIVE

    def test_record_has_created_at_timestamp(self):
        """created_at is set and UTC-aware."""
        recommender = Recommender()
        recs = recommender.generate_recommendations(_make_zombie_metrics())
        record = RecommendationRecord.from_recommendation(recs[0])

        assert record.created_at is not None
        assert record.created_at.tzinfo is not None


# ---------------------------------------------------------------------------
# Step 3: Persistence to SQLite
# ---------------------------------------------------------------------------


class TestRecommendationPersistence:
    """Records can be saved to and retrieved from SQLite."""

    @pytest.mark.asyncio
    async def test_save_and_retrieve_recommendation(self, sqlite_repos):
        """A saved recommendation is retrievable from the repository."""
        _, _, _, reco_repo = sqlite_repos

        recommender = Recommender()
        recs = recommender.generate_recommendations(_make_zombie_metrics())
        records = [RecommendationRecord.from_recommendation(r) for r in recs]

        count = await reco_repo.save_recommendations(records)
        assert count == len(records)

        start = datetime(2020, 1, 1, tzinfo=timezone.utc)
        end = datetime(2099, 1, 1, tzinfo=timezone.utc)
        saved = await reco_repo.get_recommendations(start=start, end=end)
        assert len(saved) == len(records)

    @pytest.mark.asyncio
    async def test_saved_record_has_database_id(self, sqlite_repos):
        """After saving, records have an auto-assigned database id."""
        _, _, _, reco_repo = sqlite_repos

        record = RecommendationRecord(
            pod_name="zombie-pod",
            namespace="staging",
            type=RecommendationType.ZOMBIE_POD,
            description="Test zombie",
        )
        await reco_repo.save_recommendations([record])

        start = datetime(2020, 1, 1, tzinfo=timezone.utc)
        end = datetime(2099, 1, 1, tzinfo=timezone.utc)
        saved = await reco_repo.get_recommendations(start=start, end=end)

        assert saved[0].id is not None
        assert isinstance(saved[0].id, int)
        assert saved[0].id > 0

    @pytest.mark.asyncio
    async def test_filter_by_type(self, sqlite_repos):
        """Filtering by recommendation type returns only matching records."""
        _, _, _, reco_repo = sqlite_repos

        await reco_repo.save_recommendations(
            [
                RecommendationRecord(
                    pod_name="zombie-pod",
                    namespace="staging",
                    type=RecommendationType.ZOMBIE_POD,
                    description="Zombie",
                ),
                RecommendationRecord(
                    pod_name="cpu-pod",
                    namespace="prod",
                    type=RecommendationType.RIGHTSIZING_CPU,
                    description="Oversized CPU",
                ),
            ]
        )

        start = datetime(2020, 1, 1, tzinfo=timezone.utc)
        end = datetime(2099, 1, 1, tzinfo=timezone.utc)
        zombies = await reco_repo.get_recommendations(start=start, end=end, rec_type="ZOMBIE_POD")

        assert len(zombies) == 1
        assert zombies[0].type == RecommendationType.ZOMBIE_POD

    @pytest.mark.asyncio
    async def test_filter_by_namespace(self, sqlite_repos):
        """Filtering by namespace returns only matching records."""
        _, _, _, reco_repo = sqlite_repos

        await reco_repo.save_recommendations(
            [
                RecommendationRecord(
                    pod_name="pod-a",
                    namespace="prod",
                    type=RecommendationType.ZOMBIE_POD,
                    description="Prod zombie",
                ),
                RecommendationRecord(
                    pod_name="pod-b",
                    namespace="staging",
                    type=RecommendationType.ZOMBIE_POD,
                    description="Staging zombie",
                ),
            ]
        )

        start = datetime(2020, 1, 1, tzinfo=timezone.utc)
        end = datetime(2099, 1, 1, tzinfo=timezone.utc)
        prod_recs = await reco_repo.get_recommendations(start=start, end=end, namespace="prod")

        assert len(prod_recs) == 1
        assert prod_recs[0].namespace == "prod"

    @pytest.mark.asyncio
    async def test_node_recommendations_are_upserted_per_node(self, sqlite_repos):
        """Node-scope recommendations with the same type must not collapse into one row."""
        _, _, _, reco_repo = sqlite_repos

        await reco_repo.upsert_recommendations(
            [
                RecommendationRecord(
                    scope="node",
                    target_node="node-a",
                    type=RecommendationType.UNDERUTILIZED_NODE,
                    description="Node A is underutilized",
                ),
                RecommendationRecord(
                    scope="node",
                    target_node="node-b",
                    type=RecommendationType.UNDERUTILIZED_NODE,
                    description="Node B is underutilized",
                ),
            ]
        )

        active = await reco_repo.get_active_recommendations()

        assert {r.target_node for r in active} == {"node-a", "node-b"}

    @pytest.mark.asyncio
    async def test_reconcile_marks_missing_active_recommendations_stale(self, sqlite_repos):
        """Active recommendations absent from the latest generation should stop being active."""
        _, _, _, reco_repo = sqlite_repos

        await reco_repo.upsert_recommendations(
            [
                RecommendationRecord(
                    scope="workload",
                    pod_name="api",
                    namespace="prod",
                    type=RecommendationType.RIGHTSIZING_CPU,
                    description="Old active recommendation",
                )
            ]
        )

        stale_count = await reco_repo.reconcile_active_recommendations([], namespace="prod")
        active = await reco_repo.get_active_recommendations(namespace="prod")
        history = await reco_repo.get_recommendations(
            start=datetime(2020, 1, 1, tzinfo=timezone.utc),
            end=datetime(2099, 1, 1, tzinfo=timezone.utc),
            namespace="prod",
        )

        assert stale_count == 1
        assert active == []
        assert history[0].status == RecommendationStatus.STALE


# ---------------------------------------------------------------------------
# Step 4: API retrieval
# ---------------------------------------------------------------------------


class TestRecommendationAPIRetrieval:
    """Recommendations saved to SQLite are returned by the API."""

    @pytest.mark.asyncio
    async def test_active_recommendations_returned_by_api(self, lifecycle_client):
        """Active recommendations saved to DB are returned via /recommendations/active."""
        client, reco_repo = lifecycle_client

        # Save records directly (bypassing live generation which needs metrics in DB)
        records = [
            RecommendationRecord(
                pod_name="zombie-pod",
                namespace="staging",
                type=RecommendationType.ZOMBIE_POD,
                description="Zombie pod found via recommender",
                priority="high",
                potential_savings_cost=0.50,
                status=RecommendationStatus.ACTIVE,
                created_at=datetime.now(timezone.utc),
            )
        ]
        await reco_repo.save_recommendations(records)

        resp = client.get("/api/v1/recommendations/active")
        assert resp.status_code == 200
        data = resp.json()
        assert len(data) >= 1

        types = [r["type"] for r in data]
        assert "ZOMBIE_POD" in types

    @pytest.mark.asyncio
    async def test_recommendations_history_populated_after_save(self, lifecycle_client):
        """History endpoint returns saved records after they are written."""
        client, reco_repo = lifecycle_client

        record = RecommendationRecord(
            pod_name="zombie-pod",
            namespace="staging",
            type=RecommendationType.ZOMBIE_POD,
            description="Test zombie",
            created_at=datetime(2026, 3, 15, 12, 0, 0, tzinfo=timezone.utc),
        )
        await reco_repo.save_recommendations([record])

        resp = client.get(
            "/api/v1/recommendations/history",
            params={"start": "2026-01-01T00:00:00Z", "end": "2026-12-31T00:00:00Z"},
        )
        assert resp.status_code == 200
        data = resp.json()
        assert len(data) == 1
        assert data[0]["pod_name"] == "zombie-pod"
        assert data[0]["status"] == "active"


# ---------------------------------------------------------------------------
# Step 5: Lifecycle transitions (apply / ignore)
# ---------------------------------------------------------------------------


class TestRecommendationLifecycleTransitions:
    """Recommendations can be transitioned to applied or ignored status."""

    @pytest.mark.asyncio
    async def test_apply_recommendation_updates_status(self, lifecycle_client):
        """PATCH /api/v1/recommendations/{id}/apply changes status to 'applied'."""
        client, reco_repo = lifecycle_client

        record = RecommendationRecord(
            pod_name="cpu-pod",
            namespace="prod",
            type=RecommendationType.RIGHTSIZING_CPU,
            description="Oversized CPU",
            created_at=datetime(2026, 3, 1, tzinfo=timezone.utc),
        )
        await reco_repo.save_recommendations([record])

        # Retrieve to get the database ID
        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        end = datetime(2027, 1, 1, tzinfo=timezone.utc)
        saved = await reco_repo.get_recommendations(start=start, end=end)
        rec_id = saved[0].id

        resp = client.patch(
            f"/api/v1/recommendations/{rec_id}/apply",
            json={
                "actual_cpu_request_millicores": 300,
                "notes": "Applied via automation",
            },
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "applied"
        assert data["actual_cpu_request_millicores"] == 300

    @pytest.mark.asyncio
    async def test_apply_recommendation_scales_realized_savings_for_partial_cpu_rightsizing(self, lifecycle_client):
        """Partial CPU rightsizing should prorate realized savings when actual values differ."""
        client, reco_repo = lifecycle_client

        record = RecommendationRecord(
            pod_name="cpu-pod",
            namespace="prod",
            type=RecommendationType.RIGHTSIZING_CPU,
            description="Oversized CPU",
            current_cpu_request_millicores=200,
            recommended_cpu_request_millicores=20,
            potential_savings_cost=180.0,
            potential_savings_co2e_grams=900.0,
            created_at=datetime(2026, 3, 1, tzinfo=timezone.utc),
        )
        await reco_repo.save_recommendations([record])

        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        end = datetime(2027, 1, 1, tzinfo=timezone.utc)
        saved = await reco_repo.get_recommendations(start=start, end=end)
        rec_id = saved[0].id

        resp = client.patch(
            f"/api/v1/recommendations/{rec_id}/apply",
            json={"actual_cpu_request_millicores": 30},
        )

        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "applied"
        assert data["actual_cpu_request_millicores"] == 30
        assert data["cost_saved"] == pytest.approx(170.0)
        assert data["carbon_saved_co2e_grams"] == pytest.approx(850.0)

    @pytest.mark.asyncio
    async def test_ignore_recommendation_updates_status(self, lifecycle_client):
        """PATCH /api/v1/recommendations/{id}/ignore changes status to 'ignored'."""
        client, reco_repo = lifecycle_client

        record = RecommendationRecord(
            pod_name="zombie-pod",
            namespace="staging",
            type=RecommendationType.ZOMBIE_POD,
            description="Zombie pod",
            created_at=datetime(2026, 3, 1, tzinfo=timezone.utc),
        )
        await reco_repo.save_recommendations([record])

        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        end = datetime(2027, 1, 1, tzinfo=timezone.utc)
        saved = await reco_repo.get_recommendations(start=start, end=end)
        rec_id = saved[0].id

        resp = client.patch(
            f"/api/v1/recommendations/{rec_id}/ignore",
            json={"reason": "This pod is intentionally kept warm"},
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "ignored"
        assert "intentionally" in data["ignored_reason"]

    @pytest.mark.asyncio
    async def test_apply_nonexistent_recommendation_returns_404(self, lifecycle_client):
        """Applying a non-existent recommendation ID returns 404."""
        client, _ = lifecycle_client

        resp = client.patch(
            "/api/v1/recommendations/99999/apply",
            json={"actual_cpu_request_millicores": 100},
        )
        assert resp.status_code == 404

    @pytest.mark.asyncio
    async def test_ignore_nonexistent_recommendation_returns_404(self, lifecycle_client):
        """Ignoring a non-existent recommendation ID returns 404."""
        client, _ = lifecycle_client

        resp = client.patch(
            "/api/v1/recommendations/99999/ignore",
            json={"reason": "Not applicable"},
        )
        assert resp.status_code == 404

    @pytest.mark.asyncio
    async def test_savings_summary_reflects_applied_records(self, lifecycle_client):
        """The savings summary endpoint aggregates savings from applied recommendations."""
        client, reco_repo = lifecycle_client

        record = RecommendationRecord(
            pod_name="cpu-pod",
            namespace="prod",
            type=RecommendationType.RIGHTSIZING_CPU,
            description="Oversized CPU",
            potential_savings_cost=0.50,
            potential_savings_co2e_grams=25.0,
            created_at=datetime(2026, 3, 1, tzinfo=timezone.utc),
        )
        await reco_repo.save_recommendations([record])

        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        end = datetime(2027, 1, 1, tzinfo=timezone.utc)
        saved = await reco_repo.get_recommendations(start=start, end=end)
        rec_id = saved[0].id

        # Apply the recommendation
        client.patch(f"/api/v1/recommendations/{rec_id}/apply", json={"actual_cpu_request_millicores": 200})

        # Check that savings summary reflects the applied data
        resp = client.get("/api/v1/recommendations/savings")
        assert resp.status_code == 200
