{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "greenkube.fullname" . }}
  labels:
    {{- include "greenkube.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "greenkube.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ if eq .Values.profile "production" }}{{ include "greenkube.componentServiceAccountName" (dict "context" . "component" "controller") }}{{ else }}{{ include "greenkube.serviceAccountName" . }}{{ end }}
  namespace: {{ .Release.Namespace }}
{{- if eq .Values.profile "production" }}
- kind: ServiceAccount
  name: {{ include "greenkube.componentServiceAccountName" (dict "context" . "component" "api") }}
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: {{ include "greenkube.componentServiceAccountName" (dict "context" . "component" "automation") }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}