{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "greenkube.fullname" . }}-postgres
  labels:
    {{- include "greenkube.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "greenkube.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
