apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greenkube.fullname" . }}
  labels:
    {{- include "greenkube.labels" . | nindent 4 }}
type: Opaque
data:
  # --- REQUIRED ---
  # Set this value in values.yaml or --set secrets.electricityMapsToken=YOUR_TOKEN
  {{- if .Values.secrets.electricityMapsToken }}
  ELECTRICITY_MAPS_TOKEN: {{ .Values.secrets.electricityMapsToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.boaviztaToken }}
  BOAVIZTA_TOKEN: {{ .Values.secrets.boaviztaToken | b64enc | quote }}
  {{- end }}

  # --- Database Auth ---
  {{- if .Values.secrets.dbConnectionString }}
  DB_CONNECTION_STRING: {{ .Values.secrets.dbConnectionString | b64enc | quote }}
  {{- end }}

  # --- Prometheus Auth ---
  {{- if .Values.secrets.prometheus.username }}
  PROMETHEUS_USERNAME: {{ .Values.secrets.prometheus.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.prometheus.password }}
  PROMETHEUS_PASSWORD: {{ .Values.secrets.prometheus.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.prometheus.bearerToken }}
  PROMETHEUS_BEARER_TOKEN: {{ .Values.secrets.prometheus.bearerToken | b64enc | quote }}
  {{- end }}

  # --- Elasticsearch Auth ---
  {{- if .Values.secrets.elasticsearch.user }}
  ELASTICSEARCH_USER: {{ .Values.secrets.elasticsearch.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.elasticsearch.password }}
  ELASTICSEARCH_PASSWORD: {{ .Values.secrets.elasticsearch.password | b64enc | quote }}
  {{- end }}
