apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greenkube.fullname" . }}
  labels:
    {{- include "greenkube.labels" . | nindent 4 }}
type: Opaque
data:
  # --- REQUIRED ---
  # Set this value in values.yaml or --set secrets.electricityMapsToken=YOUR_TOKEN
  ELECTRICITY_MAPS_TOKEN: {{ .Values.secrets.electricityMapsToken | b64enc | quote }}

  # --- Prometheus Auth ---
  PROMETHEUS_USERNAME: {{ .Values.secrets.prometheus.username | b64enc | quote }}
  PROMETHEUS_PASSWORD: {{ .Values.secrets.prometheus.password | b64enc | quote }}
  PROMETHEUS_BEARER_TOKEN: {{ .Values.secrets.prometheus.bearerToken | b64enc | quote }}

  # --- Elasticsearch Auth ---
  # Use secrets.elasticsearch.user, not values.elasticsearch.auth.user
  ELASTICSEARCH_USER: {{ .Values.secrets.elasticsearch.user | b64enc | quote }}
  ELASTICSEARCH_PASSWORD: {{ .Values.secrets.elasticsearch.password | b64enc | quote }}