{{- if and .Values.serviceAccount.create (ne .Values.profile "production") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "greenkube.serviceAccountName" . }}
  labels:
    {{- include "greenkube.labels" . | nindent 4 }}
{{- end }}
{{- if and .Values.serviceAccount.create (eq .Values.profile "production") }}
{{- range $component := list "api" "controller" "automation" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "greenkube.componentServiceAccountName" (dict "context" $ "component" $component) }}
  labels:
    {{- include "greenkube.labels" $ | nindent 4 }}
{{- end }}
{{- end }}